### ISSUE TITLE
All logs written to watchdog.log

### ISSUE THREAD

**Issue by maxhaslbeck** [maxhaslbeck/proving-contest-backends#12]
All logs seem to be written to watchdog.log, not separated into different files;

maybe logging.basicConfig sets the file globally,

* use one logging file?

**Comment by wimmers** [comment]
We now use one file `poller.log` for the poller/watchdog log,
and one file `grader.log` for the grader log.
See: 148b212a0f3da46609ccc5a4bdd0ba9e0dd61511
